spring:
  profiles:
    active: dev

---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: springcloud-config-eureka


#Eureka
eureka:
  instance:
    #服务端实例名
    hostname: eureka7001.com
  client:
    #是否向服务中心注册自己
    register-with-eureka: false
    #false 为注册中心
    fetch-registry: false
    #监控页面
    service-url:
      #单机 http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://eureka7101.com:7101/eureka/,http://eureka7102.com:7102/eureka/,http://eureka7103.com:7103/eureka/
---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: springcloud-config-eureka


#Eureka
eureka:
  instance:
    #服务端实例名
    hostname: eureka7001.com
  client:
    #是否向服务中心注册自己
    register-with-eureka: false
    #false 为注册中心
    fetch-registry: false
    #监控页面
    service-url:
      #单机 http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
