spring:
  profiles:
    active: dev

---
 
server:
  port: 8001

mybatis:
  #mybatis核心配置文件位置(无特殊需求不用配)
  # config-location: classpath:mybatis/mybatis-config.xml
  #扫描mapper
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 扫描pojo
  type-aliases-package: com.kuang.springcloud.pojo
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
spring:
  profiles: dev
  application:
    name: springcloud-config-provider-dep
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#Eureka配置
eureka:
  client:
    service-url:
      #注册到这个地址
      # 单机    defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


  #修改Rureka默认描述信息(可选)
  instance:
    instance-id: springcloud-provider-dep8001

#点上面springcloud-provider-dep8001链接,出来的描述信息(没什么用)
info:
  app.name: wohaoshuai
  company: com.xiajiwangluo.shen
---
 
server:
  port: 8001

mybatis:
  #mybatis核心配置文件位置(无特殊需求不用配)
  # config-location: classpath:mybatis/mybatis-config.xml
  #扫描mapper
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 扫描pojo
  type-aliases-package: com.kuang.springcloud.pojo
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
spring:
  profiles: test
  application:
    name: springcloud-config-provider-dep
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#Eureka配置
eureka:
  client:
    service-url:
      #注册到这个地址
      # 单机    defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


  #修改Rureka默认描述信息(可选)
  instance:
    instance-id: springcloud-provider-dep8001

#点上面springcloud-provider-dep8001链接,出来的描述信息(没什么用)
info:
  app.name: wohaoshuai
  company: com.xiajiwangluo.shen
---