spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-provider-dep
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7101.com:7101/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-provider-dep
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7101.com:7101/eureka/ 
